### PR TITLE
feat(permissions): allow username string to be passed to hasPermissions

### PR DESCRIPTION
**Pull request by anotherchrisberry**
When using Fiat, I keep tripping up and fetching the authentication from within another thread via `SecurityContextHolder.getContext().getAuthentication()`, which gives me a null authentication object.

Kork provides a `AuthenticatedRequest.getSpinnakerUser()` mechanism to get the username, so I've been creating an anonymous overriding horrible Authentication object to pass to Fiat. But Fiat just cares about the username, so...how about a method that just takes that?

### CODE REVIEW

**Comment by ttomsu** [comment]
I don't think this will work as written: Spring auto-injects the `Authentication` object as the first argument to `hasPermission` - which is why you had to remove the `@Overrides`. You can see from [an example callsite](https://github.com/spinnaker/clouddriver/blob/273e3f0fe1b0e5bddd43ca7a9abcba68a2f1801f/clouddriver-web/src/main/groovy/com/netflix/spinnaker/clouddriver/controllers/JobController.groovy#L42) that the authentication object isn't there.

If the authentication object is null, but Kork is still returning a non-null `getSpinnakerUser()` (which is stored in Logback's MDC), then there's a piece missing somewhere that connects the two together.

**Comment by anotherchrisberry** [comment]
This isn't meant to be used in an annotation - only via [explicit](https://github.com/spinnaker/clouddriver/blob/e3892b32751a0007fa22b7bd12a6366b2305ff52/clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/search/ApplicationSearchProvider.groovy#L72) [calls](https://github.com/spinnaker/clouddriver/blob/7bb790eeb387d7514f4d7d2382b250a968586704/clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/CatsSearchProvider.groovy#L177) via the `FiatPermissionEvaluator`. The `@Overrides` wasn't really removed (it's on the next method), it just looks like that because of git's diffing.

**Comment by ttomsu** [comment]
Ahh, you're right, my mistake.

**Comment by maggieneterval** [comment]
Hey @anotherchrisberry & @ttomsu! I am trying to help a user experiencing an issue with the /search endpoint where getting the authentication from `SecurityContextHolder.context.authentication` returns null in Clouddriver [here](https://github.com/spinnaker/clouddriver/blob/master/clouddriver-core/src/main/groovy/com/netflix/spinnaker/clouddriver/cache/CatsSearchProvider.groovy#L166), which is throwing an NPE downstream in Fiat from within the `getUsername` method (this is a 1.14-specific problem). I'm curious if y'all know of any workaround here, or if there's some other way we should be supplying the auth object to Fiat in the post-Spring-update world. I'm not very familiar with Fiat or Spring security so any insight here is much appreciated!

**Pull request merged**
