### PR TITLE
fix(redis): Use byte[] instead of String

### PR DESCRIPTION
**Pull request by deverton**
Change the `RedisPermissionsRepository` to use `byte[]` instead of `String` when communicating with Redis. This reduces memory usage with larger permission sets.

### CODE REVIEW

**Review by robzienert — APPROVED** [review]
Nice!

**Comment by th3morg** [comment]
@deverton It looks like this has approval, but conflicts need to be resolved before it can be merged.

**Comment by deverton** [comment]
@th3morg should be good to go now.

**Comment by Nessex** [comment]
FYI: I've added some rough performance measurement data that is relevant to this PR over here: 

https://github.com/spinnaker/fiat/pull/841#issuecomment-792738769

This change took a whole minute off a 6+ minute sync 👍

**Review by cfieber — APPROVED** [review]

**Pull request merged**
