### PR TITLE
fix(apps): Clear resource provider caches to ensure up-to-date data

### PR DESCRIPTION
**Pull request by ncknt**
Cherry pick of https://github.com/spinnaker/fiat/pull/409

### CODE REVIEW

**Comment by ncknt** [comment]
@ezimanyi Can we cherry pick the Fiat sync fix for 1.14.x? Thinking of doing 1.13.x as well. BTW I can't merge my PRs.

**Comment by ezimanyi** [comment]
I'll defer to @dibyom who understands this change better than I do and @maggieneterval who's the release manager about whether this makes sense to cherry-pick.

**Comment by maggieneterval** [comment]
Seems reasonable to cherry-pick since it's a fix (for the problem of the cache being in an inconsistent state when creating an application within 20 seconds of another, if I'm understanding correctly). @dibyom do you foresee any potential unexpected issues with this change or is the blast radius minimal?

**Comment by dibyom** [comment]
+1 for cherry-picking this!

**Pull request merged**
