### PR TITLE
fix: add migration to ensure consistency between resource_name in fiat_resource and fiat_permission tables

### PR DESCRIPTION
**Pull request by armory-abedonik**
Add migration to ensure consistency between resource_name in fiat_resource and fiat_permission tables.

**References:**
* https://github.com/spinnaker/fiat/pull/963

### CODE REVIEW

**Review by mrampton — APPROVED** [review]

**Comment by armory-abedonik** [comment]
Hi @mattgogerly, please check this pull request and merge if everything is fine. 🙏

**Review by mattgogerly — APPROVED** [review]

**Comment by armory-abedonik** [comment]
Hi @mattgogerly, please merge this pull request if you don't have any objects. I don't have permissions to do it myself. Thank you in advance!

**Comment by mattgogerly** [comment]
> Hi @mattgogerly, please merge this pull request if you don't have any objects. I don't have permissions to do it myself. Thank you in advance!

I'm just waiting a bit to see if any other approvers have any comments, Fiat isn't my area of expertise.

**Comment by armory-abedonik** [comment]
Hi @cfieber, @jonsie Please take a look at this pull request and merge it if you don't have any objections. Thank you in advance!

**Comment by mattgogerly** [comment]
@dogonthehorizon @dbyron-sf @kskewes-sf @link108 @jasonmcintosh anybody see anything obviously problematic with this? I think this might be a resolution for the issue some people were seeing with Liquibase migrations from 1.26 -> 1.27. Otherwise I'll go ahead and merge.

**Review by dbyron-sf — APPROVED** [review]

**Comment by mattgogerly** [comment]
@Mergifyio update

**Comment by link108** [comment]
We are seeing a users have issues upgrading from 1.26 -> 1.27, I'm going to backport both this and https://github.com/spinnaker/fiat/pull/963

**Comment by link108** [comment]
@mergifyio backport release-1.27.x release-1.28.x

**Pull request merged**
